---
ansible_python_interpreter: /usr/bin/python3
username: fscotto
user_group: fscotto
user_home: "/home/{{ username }}"
user_shell: /bin/bash
effective_username: "{{ username }}"
effective_user_group: "{{ user_group }}"
effective_user_home: "{{ user_home }}"

xdg_user_directories:
  - Desktop
  - Documents
  - Downloads
  - Music
  - Pictures
  - Public
  - Templates
  - Videos

common_packages:
  - bash-completion
  - bat
  - entr
  - fzf
  - git
  - jq
  - tree
  - unzip
  - vim
  - wget
  - zip
  - zoxide

common_dotfiles:
  - name: .bashrc
    src: .bashrc
    dest: .bashrc
    mode: "0644"
  - name: .bash_profile
    src: .bash_profile
    dest: .bash_profile
    mode: "0644"
  - name: .bashrc.aliases
    src: .bashrc.aliases
    dest: .bashrc.aliases
    mode: "0644"
  - name: .vimrc
    src: .vimrc
    dest: .vimrc
    mode: "0644"
  - name: bat config
    src: .config/bat/.config/bat/
    dest: .config/bat/
    mode: preserve
