---
arch_packages_base:
  - 7zip
  - archlinux-keyring
  - avahi
  - base-devel
  - bluez
  - clang
  - cmake
  - cups
  - cups-filters
  - cups-pk-helper
  - fastfetch
  - flatpak
  - fuse3
  - gcc
  - gdb
  - git-delta
  - github-cli
  - gnome-keyring
  - go
  - gvfs
  - gvfs-mtp
  - gvfs-smb
  - imagemagick
  - isync
  - libsecret
  - libtool
  - linux
  - linux-headers
  - lm_sensors
  - man-db
  - man-pages
  - msmtp
  - mu
  - networkmanager
  - nodejs
  - npm
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - pkgconf
  - plocate
  - podman
  - podman-compose
  - rclone
  - sane
  - sane-airscan
  - seahorse
  - simple-scan
  - speech-dispatcher
  - syncthing
  - system-config-printer
  - tealdeer
  - tmux
  - tree-sitter-cli
  - ufw
  - wireplumber
  - xdotool
  - yt-dlp

arch_desktop_common_packages:
  - brightnessctl
  - dex
  - pinentry
  - udiskie
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk
  - xdg-user-dirs

arch_desktop_gnome_packages:
  - gdm
  - gnome-control-center
  - gnome-session
  - gnome-settings-daemon
  - gnome-shell
  - gnome-shell-extensions
  - gnome-tweaks
  - mutter
  - nautilus
  - xdg-desktop-portal-gnome

arch_profile_packages:
  - alacritty
  - bridge-utils
  - deluge
  - dnsmasq
  - edk2-ovmf
  - emacs
  - ffmpegthumbnailer
  - firefox
  - fontconfig
  - freetype2
  - gufw
  - libvterm
  - libx11
  - libxft
  - libvirt
  - libreoffice-fresh
  - meld
  - mpv
  - noto-fonts
  - noto-fonts-emoji
  - pdfarranger
  - playerctl
  - poppler
  - poppler-glib
  - qemu-desktop
  - remmina
  - ripgrep
  - rsync
  - ruff
  - rustup
  - texlive-basic
  - texlive-binextra
  - texlive-latex
  - texlive-latexextra
  - ttf-liberation
  - ttf-nerd-fonts-symbols
  - universal-ctags
  - uv
  - virt-manager
  - xarchiver
  - xournalpp
  - zstd

enabled_services:
  - NetworkManager
  - avahi-daemon
  - bluetooth
  - cups
  - gdm
  - libvirtd
  - ufw

desktop_systemd_user_services:
  - ssh-agent.service
  - emacs.service
  - syncthing.service
  - rclone-pcloud.service
