---
profile_packages:
  - i3
  - i3blocks
  - i3blocks-blocklets
  - i3status
  - i3lock-color
  - dex
  - dunst
  - rofi
  - alacritty
  - Thunar
  - exo
  - thunar-volman
  - udiskie
  - xfce-polkit
  - xfce4-power-manager
  - xfce4-clipman-plugin
  - xfce4-screenshooter
  - volumeicon
  - brightnessctl
  - feh
  - ImageMagick
  - scrot
  - xclip
  - xss-lock
  - playerctl
  - nerd-fonts-symbols-ttf
  - network-manager-applet
  - chromium
  - emacs-gtk3
  - mu4e
  - isync
  - msmtp
  - libsecret
  - libtool
  - libvterm-devel
  - cmake
  - gcc
  - gdb
  - pkg-config
  - libX11-devel
  - libXft-devel
  - fontconfig-devel
  - freetype-devel
  - go
  - clang
  - clang-tools-extra
  - mpv
  - celluloid
  - yt-dlp
  - shotwell
  - ristretto
  - xournalpp
  - pdfarranger
  - remmina
  - deluge-gtk
  - xarchiver
  - gufw
  - ufw
  - meld
  - 7zip
  - libreoffice
  - lm_sensors
  - fastfetch
  - liberation-fonts-ttf
  - terminus-font
  - blueman
  - bluez
  - libspa-bluetooth
  - yaru
  - yaru-plus

desktop_dotfiles:
  - name: i3 config
    src: .config/i3/
    dest: .config/i3/
    mode: preserve
  - name: i3blocks config
    src: .config/i3blocks/
    dest: .config/i3blocks/
    mode: preserve
  - name: dunst config
    src: .config/dunst/
    dest: .config/dunst/
    mode: preserve
  - name: alacritty config
    src: .config/alacritty/
    dest: .config/alacritty/
    mode: preserve
  - name: Thunar config
    src: .config/Thunar/
    dest: .config/Thunar/
    mode: preserve
  - name: rofi config
    src: .config/rofi/
    dest: .config/rofi/
    mode: preserve
  - name: fastfetch config
    src: .config/fastfetch/
    dest: .config/fastfetch/
    mode: preserve
  - name: fontconfig fallback
    src: .config/fontconfig/
    dest: .config/fontconfig/
    mode: preserve
  - name: yt-dlp config
    src: .config/yt-dlp/
    dest: .config/yt-dlp/
    mode: preserve
  - name: .xinitrc
    src: .xinitrc
    dest: .xinitrc
    mode: "0644"
  - name: .gitconfig
    src: .gitconfig
    dest: .gitconfig
    mode: "0644"
  - name: .gitignore_global
    src: .gitignore_global
    dest: .gitignore_global
    mode: "0644"
  - name: .themes.gitignore
    src: .themes.gitignore
    dest: .themes.gitignore
    mode: "0644"
  - name: .mbsyncrc
    src: .mbsyncrc
    dest: .mbsyncrc
    mode: "0600"
  - name: .msmtprc
    src: .msmtprc
    dest: .msmtprc
    mode: "0600"
  - name: Emacs config
    src: .emacs.d/
    dest: .emacs.d/
    mode: preserve

desktop_flatpak_packages:
  - be.alexandervanhee.gradia
  - ch.protonmail.protonmail-bridge
  - com.discordapp.Discord
  - com.calibre_ebook.calibre
  - com.github.tchx84.Flatseal
  - com.spotify.Client
  - io.github.flattool.Warehouse
  - org.telegram.desktop
  - sh.loft.devpod
