---
profile_packages:
  - i3
  - i3blocks
  - i3blocks-blocklets
  - i3status
  - i3lock-color
  - dunst
  - rofi
  - alacritty
  - Thunar
  - thunar-volman
  - udiskie
  - xfce-polkit
  - xfce4-power-manager
  - xfce4-clipman-plugin
  - xfce4-screenshooter
  - volumeicon
  - brightnessctl
  - feh
  - scrot
  - xclip
  - network-manager-applet
  - chromium
  - mpv
  - libreoffice
  - lm_sensors
  - fastfetch
  - liberation-fonts-ttf
  - terminus-font
  - blueman
  - bluez
  - libspa-bluetooth
  - yaru
  - yaru-plus

desktop_flatpak_packages:
  - ch.protonmail.protonmail-bridge
  - com.calibre_ebook.calibre
  - com.github.tchx84.Flatseal
  - com.spotify.Client
  - io.github.flattool.Warehouse
  - org.telegram.desktop
