---
fedora_packages_base:
  - curl
  - flatpak
  - gcc
  - gcc-c++
  - git-delta
  - htop
  - jq
  - make
  - nodejs
  - ripgrep

fedora_manage_docker_repo: true

fedora_emacs_packages:
  - emacs-pgtk
  - pandoc
  - latexmk
  - texlive-latex
  - texlive-luatex
  - texlive-collection-latexrecommended

fedora_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

enabled_services:
  - firewalld

fedora_dotfiles:
  - src: .bashrc.d/
    dest: .bashrc.d/
    mode: preserve
  - src: .gtkrc-2.0
    dest: .gtkrc-2.0
    mode: "0644"
  - src: .config/gtk-3.0/
    dest: .config/gtk-3.0/
    mode: preserve
  - src: .config/gtk-4.0/
    dest: .config/gtk-4.0/
    mode: preserve

workstation_firewall_backend: firewalld

fedora_dev_packages:
  - croc
  - distrobox
  - gnupg
  - gnupg2-gpg-agent
  - libfido2
  - openssh-clients
  - shellcheck

fedora_flatpak_remote_name: flathub
fedora_flatpak_remote_url: https://dl.flathub.org/repo/flathub.flatpakrepo
