---
platform_profile: rocky
platform_family: redhat
platform_package_manager: dnf
platform_service_manager: systemd

rocky_openzfs_release_rpm: https://zfsonlinux.org/epel/zfs-release-3-0.el9.noarch.rpm
rocky_syncthing_version: 2.1.3
rocky_syncthing_archive_checksum: sha256:f929eb8e5b72a85543eeeefb2c38f34a68e0c530e70758a2905b78840c76602c
rocky_syncthing_archive_url: >-
  {{
    'https://github.com/syncthing/syncthing/releases/download/v'
    ~ rocky_syncthing_version
    ~ '/syncthing-linux-amd64-v'
    ~ rocky_syncthing_version
    ~ '.tar.gz'
  }}

rocky_manage_openzfs_repo: false
rocky_manage_syncthing_binary: false
rocky_manage_docker_repo: false
rocky_manage_github_cli_repo: false

rocky_docker_repo_url: https://download.docker.com/linux/rhel/docker-ce.repo
rocky_docker_repo_file: /etc/yum.repos.d/docker-ce.repo
rocky_github_cli_repo_url: https://cli.github.com/packages/rpm/gh-cli.repo
rocky_github_cli_repo_file: /etc/yum.repos.d/gh-cli.repo

enabled_services:
  - firewalld

rocky_common_packages:
  - bash-completion
  - bat
  - fzf
  - git
  - jq
  - tree
  - unzip
  - vim-enhanced
  - wget
  - zip
  - zoxide

rocky_packages_base:
  - dnf-plugins-core
  - firewalld
  - openssh-server
  - rsync
  - sudo

rocky_profile_packages: []
rocky_docker_packages: []
rocky_docker_conflicting_packages: []
