---
platform_profile: void
platform_family: void
platform_package_manager: xbps
platform_service_manager: runit

vim_plugin_distro_packages:
  - fzf
vim_plugin_source_plugins:
  - name: fzf
    repo: https://github.com/junegunn/fzf.git
    version: v0.72.0
  - name: fzf.vim
    repo: https://github.com/junegunn/fzf.vim.git
    version: 34a564c81f36047f50e593c1656f4580ff75ccca
  - name: vim-fugitive
    repo: https://github.com/tpope/vim-fugitive.git
    version: 3b753cf8c6a4dcde6edee8827d464ba9b8c4a6f0
