---
rocky_manage_podman: true
rocky_manage_github_cli_repo: true

rocky_profile_packages:
  - avahi
  - curl
  - dmidecode
  - dosfstools
  - gcc
  - gcc-c++
  - git-delta
  - gh
  - gnupg2
  - htop
  - make
  - nmap-ncat
  - nodejs
  - parted
  - pciutils
  - pinentry
  - ranger
  - ripgrep

rocky_podman_packages:
  - podman
  - podman-compose

enabled_services:
  - firewalld
  - podman.socket

server_firewall_backend: firewalld
server_firewalld_zone: public
server_firewalld_services:
  - ssh
  - cockpit
  - http
  - https
server_firewalld_ports: []
server_sshd_service_name: sshd
server_compose_selinux_mount_option: Z
server_syncthing_enabled: false
