---
ubuntu_packages_base:
  - curl
  - ufw
  - htop
  - build-essential
  - nodejs
  - git-delta
  - jq

ubuntu_manage_docker_repo: true

ubuntu_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

enabled_services:
  - ufw
  - docker
