---
void_packages_base:
  - 7zip
  - NetworkManager
  - avahi
  - base-system
  - bat
  - clang
  - clang-tools-extra
  - cmake
  - cups
  - cups-filters
  - cups-pk-helper
  - delta
  - elogind
  - fastfetch
  - flatpak
  - fuse3
  - gcc
  - gdb
  - gist
  - github-cli
  - gnome-keyring
  - go
  - gvfs
  - ImageMagick
  - isync
  - libsecret
  - libtool
  - lm_sensors
  - msmtp
  - mu4e
  - network-manager-applet
  - nodejs
  - ntfs-3g
  - pavucontrol
  - pipewire
  - pkg-config
  - podman
  - podman-compose
  - rclone
  - sane
  - sane-airscan
  - seahorse
  - simple-scan
  - socklog
  - socklog-void
  - speech-dispatcher
  - syncthing
  - system-config-printer
  - tmux
  - tealdeer
  - tree-sitter-grammars
  - ufw
  - xdotool
  - void-repo-nonfree
  - vpm
  - vsv
  - xtools
  - yt-dlp
  - plocate

enabled_services:
  - NetworkManager
  - avahi-daemon
  - bluetoothd
  - cupsd
  - dbus
  - elogind
  - emptty
  - libvirtd
  - nanoklogd
  - socklog-unix
  - turnstiled
  - ufw
  - virtlockd
  - virtlogd
