---
profile_packages:
  - gnupg
  - gpg-agent
  - pcscd
  - yubikey-manager
  - pinentry-gnome3
  - openssh-client
  - libfido2-1
  - meld
  - gufw
  - libreoffice
  - network-manager-openconnect-gnome
  - gnome-shell-extension-manager
  - gnome-shell-extensions
  - gnome-tweaks
  - podman
  - podman-compose
  - distrobox

workstation_manage_google_chrome: true

workstation_removed_snap_packages:
  - firefox

workstation_snap_packages:
  - name: intellij-idea-ultimate
    classic: true
    channel: latest/stable
  - name: postman
    classic: false
    channel: latest/stable
  - name: thunderbird
    classic: false
    channel: latest/stable
  - name: code
    classic: true
    channel: latest/stable
  - name: xournalpp
    classic: false
    channel: latest/stable
  - name: pdfarranger
    classic: false
    channel: latest/stable
  - name: spotify
    classic: false
    channel: latest/stable
  - name: telegram-desktop
    classic: false
    channel: latest/stable
  - name: dbeaver-ce
    classic: true
    channel: latest/stable

workstation_user_directories:
  - path: "{{ user_home }}/.config"
    mode: "0755"
  - path: "{{ user_home }}/.local"
    mode: "0755"
  - path: "{{ user_home }}/.local/bin"
    mode: "0755"
  - path: "{{ user_home }}/.gnupg"
    mode: "0700"

workstation_dotfiles:
  - src: .gnupg/gpg-agent.conf
    dest: .gnupg/gpg-agent.conf
    mode: "0600"
  - src: .gitignore_global
    dest: .gitignore_global
    mode: "0644"
  - src: .themes.gitignore
    dest: .themes.gitignore
    mode: "0644"

workstation_templates:
  - src: workstation/.gitconfig.j2
    dest: .gitconfig
    mode: "0644"

workstation_gnome_extensions:
  - id: 9308
    uuid: bluetooth-battery-monitor@v8v88v8v88.com
    version_tag: 68559
    enabled: true
  - id: 1401
    uuid: bluetooth-quick-connect@bjarosze.gmail.com
    version_tag: 65323
    enabled: true
  - id: 6099
    uuid: paperwm@paperwm.github.com
    version_tag: 68525
    enabled: true

workstation_disabled_gnome_extensions:
  - tiling-assistant@ubuntu.com
  - ubuntu-dock@ubuntu.com
