---
workstation_dev_packages:
  - distrobox
  - gnupg
  - gpg-agent
  - libfido2-1
  - openssh-client

workstation_user_directories:
  - path: "{{ user_home }}/.config"
    mode: "0755"
  - path: "{{ user_home }}/.local"
    mode: "0755"
  - path: "{{ user_home }}/.local/bin"
    mode: "0755"
  - path: "{{ user_home }}/.gnupg"
    mode: "0700"

workstation_dotfiles:
  - src: .gnupg/gpg-agent.conf
    dest: .gnupg/gpg-agent.conf
    mode: "0600"
  - src: .gitignore_global
    dest: .gitignore_global
    mode: "0644"
  - src: .themes.gitignore
    dest: .themes.gitignore
    mode: "0644"

workstation_templates:
  - src: workstation/.gitconfig.j2
    dest: .gitconfig
    mode: "0644"
