---
ansible_connection: psrp
ansible_psrp_auth: negotiate
ansible_psrp_cert_validation: ignore
ansible_psrp_protocol: https
ansible_port: 5986
ansible_shell_type: powershell

windows_enable_dark_theme: true
windows_hide_taskbar_search: true
windows_hide_taskbar_widgets: true
windows_terminal_default_profile_name: Ubuntu
windows_taskbar_layout_directory: 'C:\ProgramData\Infra\Windows'
windows_taskbar_layout_path: '{{ windows_taskbar_layout_directory }}\taskbar-layout.xml'
windows_taskbar_reapply_every_logon: false

windows_taskbar_pins:
  - type: desktop_application_id
    id: Chrome
  - type: desktop_application_id
    id: Microsoft.Windows.Explorer
  - type: app_user_model_id
    id: Microsoft.OutlookForWindows_8wekyb3d8bbwe!Microsoft.OutlookforWindows
  - type: app_user_model_id
    id: MSTeams_8wekyb3d8bbwe!MSTeams
  - type: app_user_model_id
    id: 5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App
  - type: desktop_application_id
    id: Telegram.TelegramDesktop
  - type: desktop_application_id
    id: Microsoft.VisualStudioCode
  - type: desktop_application_link_path
    path: '%APPDATA%\Microsoft\Windows\Start Menu\Programs\JetBrains Toolbox\IntelliJ IDEA Ultimate.lnk'
  - type: desktop_application_id
    id: com.squirrel.Postman.Postman
  - type: app_user_model_id
    id: Microsoft.WindowsTerminal_8wekyb3d8bbwe!App
  - type: desktop_application_link_path
    path: '%APPDATA%\Microsoft\Windows\Start Menu\Programs\DBeaver Community\DBeaver.lnk'

windows_winget_packages:
  - id: 7zip.7zip
    name: 7-Zip
  - id: Adobe.Acrobat.Reader.64-bit
    name: Adobe Acrobat Reader
  - id: DBeaver.DBeaver.Community
    name: DBeaver Community
  - id: Google.Chrome
    name: Google Chrome
  - id: JetBrains.IntelliJIDEA.Ultimate
    name: IntelliJ IDEA Ultimate
  - id: Logitech.OptionsPlus
    name: Logitech Options+
  - id: Microsoft.VisualStudioCode
    name: Visual Studio Code
  - id: Microsoft.WindowsTerminal
    name: Windows Terminal
  - id: Postman.Postman
    name: Postman
  - id: Telegram.TelegramDesktop
    name: Telegram Desktop
  - id: 9NKSQGP7F2NH
    name: WhatsApp
    source: msstore

windows_vscode_extensions:
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-wsl

windows_wsl_distribution_name: Ubuntu
