---
profile_packages:
  - htop
  - fastfetch
  - build-essential
  - nodejs
  - git-delta
  - meld
  - gufw
  - libreoffice
  - network-manager-openconnect-gnome
  - gnome-shell-extension-manager
  - gnome-shell-extensions
  - gnome-tweaks
  - podman
  - podman-compose
  - distrobox

workstation_manage_google_chrome: true

workstation_removed_snap_packages:
  - firefox

workstation_snap_packages:
  - name: intellij-idea-ultimate
    classic: true
    channel: latest/stable
  - name: postman
    classic: false
    channel: latest/stable
  - name: thunderbird
    classic: false
    channel: latest/stable
  - name: code
    classic: true
    channel: latest/stable
  - name: xournalpp
    classic: false
    channel: latest/stable
  - name: pdfarranger
    classic: false
    channel: latest/stable
  - name: spotify
    classic: false
    channel: latest/stable
  - name: telegram-desktop
    classic: false
    channel: latest/stable

workstation_user_directories:
  - path: "{{ user_home }}/.config"
    mode: "0755"
  - path: "{{ user_home }}/.local"
    mode: "0755"
  - path: "{{ user_home }}/.local/bin"
    mode: "0755"
