---
ansible_connection: psrp
ansible_psrp_auth: negotiate
ansible_psrp_cert_validation: ignore
ansible_psrp_protocol: https
ansible_port: 5986
ansible_shell_type: powershell

windows_enable_dark_theme: true
windows_hide_taskbar_search: true
windows_hide_taskbar_widgets: true
windows_terminal_default_profile_name: Ubuntu

windows_winget_packages:
  - id: 7zip.7zip
    name: 7-Zip
  - id: Adobe.Acrobat.Reader.64-bit
    name: Adobe Acrobat Reader
  - id: DBeaver.DBeaver.Community
    name: DBeaver Community
  - id: Google.Chrome
    name: Google Chrome
  - id: JetBrains.IntelliJIDEA.Ultimate
    name: IntelliJ IDEA Ultimate
  - id: Logitech.OptionsPlus
    name: Logitech Options+
  - id: Microsoft.VisualStudioCode
    name: Visual Studio Code
  - id: Microsoft.WindowsTerminal
    name: Windows Terminal
  - id: Postman.Postman
    name: Postman
  - id: Telegram.TelegramDesktop
    name: Telegram Desktop
  - id: 9NKSQGP7F2NH
    name: WhatsApp
    source: msstore

windows_vscode_extensions:
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-wsl

windows_wsl_distribution_name: Ubuntu
