---
enabled_services:
  - docker

workstation_dev_wsl_packages: []
workstation_dev_wsl_excluded_packages:
  - pcscd
  - pinentry-gnome3
  - podman
  - podman-compose
  - ufw
  - yubikey-manager
workstation_is_wsl: true
workstation_manage_google_chrome: false
workstation_removed_snap_packages: []
workstation_snap_packages: []
workstation_wsl_systemd_enabled: true
