---
hostname: deadalus-fedora

host_packages: []
host_enabled_services: []
workstation_firewall_backend: firewalld

workstation_host_vscode_extensions:
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-azuretools.vscode-docker
  - redhat.vscode-yaml
  - redhat.ansible

workstation_gnome_managed_settings:
  - schema: org.gnome.shell
    key: favorite-apps
    value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'com.spotify.Client.desktop', 'org.mozilla.Thunderbird.desktop', 'org.telegram.desktop.desktop', 'code.desktop', 'intellij-idea-ultimate.desktop', 'io.dbeaver.DBeaverCommunity.desktop', 'com.getpostman.Postman.desktop', 'org.gnome.Ptyxis.desktop']"
  - schema: org.gnome.shell
    key: app-picker-layout
    value: "[{'6f4bfcaf-700e-4fe3-8fd2-4a3e6fc46bcf': <{'position': <0>}>, 'System': <{'position': <1>}>, 'Utilities': <{'position': <2>}>, 'org.gnome.Contacts.desktop': <{'position': <3>}>, 'org.gnome.Weather.desktop': <{'position': <4>}>, 'org.gnome.clocks.desktop': <{'position': <5>}>, 'org.gnome.Maps.desktop': <{'position': <6>}>, 'org.gnome.SimpleScan.desktop': <{'position': <7>}>, 'org.gnome.Settings.desktop': <{'position': <8>}>, 'org.gnome.Boxes.desktop': <{'position': <9>}>, 'org.gnome.Showtime.desktop': <{'position': <10>}>, 'org.gnome.Snapshot.desktop': <{'position': <11>}>, 'org.gnome.Characters.desktop': <{'position': <12>}>, 'org.gnome.Calculator.desktop': <{'position': <13>}>, 'org.gnome.Calendar.desktop': <{'position': <14>}>, 'org.gnome.TextEditor.desktop': <{'position': <15>}>, 'org.gnome.Meld.desktop': <{'position': <16>}>, 'org.gnome.tweaks.desktop': <{'position': <17>}>, 'org.gnome.Software.desktop': <{'position': <18>}>}]"
  - schema: org.gnome.desktop.input-sources
    key: sources
    value: "[('xkb', 'us')]"
  - schema: org.gnome.desktop.interface
    key: color-scheme
    value: "'prefer-dark'"
  - schema: org.gnome.desktop.privacy
    key: report-technical-problems
    value: "false"
  - schema: org.gnome.desktop.wm.preferences
    key: button-layout
    value: "'appmenu:minimize,maximize,close'"
  - schema: org.gnome.nautilus.preferences
    key: click-policy
    value: "'double'"
  - schema: org.gnome.nautilus.preferences
    key: date-time-format
    value: "'simple'"
  - schema: org.gnome.nautilus.preferences
    key: default-folder-viewer
    value: "'icon-view'"
  - schema: org.gnome.nautilus.preferences
    key: default-sort-order
    value: "'name'"
  - schema: org.gnome.nautilus.preferences
    key: recursive-search
    value: "'local-only'"
  - schema: org.gnome.nautilus.preferences
    key: show-create-link
    value: "true"
  - schema: org.gnome.nautilus.preferences
    key: show-delete-permanently
    value: "true"
  - schema: org.gnome.nautilus.preferences
    key: show-directory-item-counts
    value: "'local-only'"
  - schema: org.gnome.nautilus.preferences
    key: show-hidden-files
    value: "false"
  - schema: org.gnome.nautilus.preferences
    key: show-image-thumbnails
    value: "'local-only'"
  - schema: org.gnome.nautilus.preferences
    key: thumbnail-limit
    value: "uint64 50"
  - schema: org.gnome.nautilus.icon-view
    key: captions
    value: "['none', 'none', 'none']"
  - schema: org.gnome.nautilus.icon-view
    key: default-zoom-level
    value: "'medium'"
  - schema: org.gtk.Settings.FileChooser
    key: clock-format
    value: "'24h'"
  - schema: org.gtk.Settings.FileChooser
    key: date-format
    value: "'regular'"
  - schema: org.gtk.Settings.FileChooser
    key: location-mode
    value: "'path-bar'"
  - schema: org.gtk.Settings.FileChooser
    key: show-hidden
    value: "false"
  - schema: org.gtk.Settings.FileChooser
    key: show-size-column
    value: "true"
  - schema: org.gtk.Settings.FileChooser
    key: show-type-column
    value: "true"
  - schema: org.gtk.Settings.FileChooser
    key: sort-column
    value: "'name'"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: clock-format
    value: "'24h'"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: date-format
    value: "'regular'"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: location-mode
    value: "'path-bar'"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: show-hidden
    value: "false"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: show-size-column
    value: "true"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: show-type-column
    value: "true"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: sort-column
    value: "'name'"
  - schema: org.gtk.gtk4.Settings.FileChooser
    key: sort-directories-first
    value: "true"
  - schema: org.gnome.TextEditor
    key: auto-indent
    value: "true"
  - schema: org.gnome.TextEditor
    key: highlight-matching-brackets
    value: "true"
  - schema: org.gnome.TextEditor
    key: indent-style
    value: "'tab'"
  - schema: org.gnome.TextEditor
    key: keybindings
    value: "'default'"
  - schema: org.gnome.TextEditor
    key: restore-session
    value: "true"
  - schema: org.gnome.TextEditor
    key: show-line-numbers
    value: "false"
  - schema: org.gnome.TextEditor
    key: spellcheck
    value: "true"
  - schema: org.gnome.TextEditor
    key: style-scheme
    value: "'Adwaita'"
  - schema: org.gnome.TextEditor
    key: style-variant
    value: "'follow'"
  - schema: org.gnome.TextEditor
    key: use-system-font
    value: "true"
  - schema: org.gnome.TextEditor
    key: wrap-text
    value: "true"
  - schema: org.gnome.desktop.background
    key: picture-uri
    value: "'file:///usr/share/backgrounds/gnome/lcd-rainbow-l.jxl'"
  - schema: org.gnome.desktop.background
    key: picture-uri-dark
    value: "'file:///usr/share/backgrounds/gnome/lcd-rainbow-d.jxl'"

workstation_gnome_extension_dconf_settings:
  - path: /org/gnome/shell/extensions/paperwm/
    key: selection-border-radius-bottom
    value: "15"
  - path: /org/gnome/shell/extensions/paperwm/
    key: selection-border-radius-top
    value: "15"
  - path: /org/gnome/shell/extensions/paperwm/
    key: selection-border-size
    value: "5"
  - path: /org/gnome/shell/extensions/paperwm/
    key: show-window-position-bar
    value: "false"
  - path: /org/gnome/shell/extensions/paperwm/
    key: show-workspace-indicator
    value: "false"
  - path: /org/gnome/shell/extensions/paperwm/
    key: window-gap
    value: "10"
