---
hostname: ikaros

desktop_sessions_enabled:
  - i3

desktop_default_session: i3
desktop_default_session_env: xorg

host_packages:
  - mesa-dri
  - vulkan-loader
  - mesa-vulkan-radeon
  - mesa-vaapi
  - xf86-video-amdgpu

host_i3_dotfiles:
  - src: .config/autorandr/
    dest: .config/autorandr/
    mode: preserve

host_enabled_services: []
