---
hostname: ikaros

host_packages:
  - mesa-dri
  - vulkan-loader
  - mesa-vulkan-radeon
  - mesa-vaapi
  - xf86-video-amdgpu

host_dotfiles:
  - src: .config/autorandr/
    dest: .config/autorandr/
    mode: preserve

host_enabled_services: []
