---
hostname: ikaros

host_packages:
  - openssh-clients
  - openssh-server
  - mesa-vulkan-drivers

host_firewalld_rich_rules:
  - rule family="ipv4" source address="192.168.0.0/24" service name="ssh" accept

host_sshd_settings:
  PermitRootLogin: "no"
  PubkeyAuthentication: "yes"
  PasswordAuthentication: "no"
  KbdInteractiveAuthentication: "no"

host_sshd_allow_users:
  - "{{ username }}"

host_authorized_ssh_keys: "{{ vault_ikaros_authorized_ssh_keys | default([]) }}"

host_enabled_services:
  - sshd
