---
hostname: nymph

host_xbps_repositories:
  - name: hyprland-void
    url: "https://raw.githubusercontent.com/Makrennel/hyprland-void/repository-x86_64-glibc"

host_emptty_wayland_sessions:
  - Hyprland.desktop

host_packages:
  - nvidia
  - mesa-dri
  - vulkan-loader
  - mesa-vulkan-intel
  - intel-video-accel
  - tlp
  - tlp-rdw
  - hyprland
  - hyprpaper
  - xdg-desktop-portal-hyprland
  - Waybar
  - wlogout

host_enabled_services:
  - tlp

host_dotfiles:
  - src: .config/autorandr/
    dest: .config/autorandr/
    mode: preserve
  - src: .config/hypr/
    dest: .config/hypr/
    mode: preserve
  - src: .config/waybar/
    dest: .config/waybar/
    mode: preserve
