# Camera priority overrides for nymph
# Make Integrated Camera (RGB) the default over Integrated IR Camera

monitor.v4l2.rules = [
  {
    matches = [
      {
        device.product.id = "0x2113"
        api.v4l2.cap.card = "Integrated Camera: Integrated C"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1100
      }
    }
  }
  {
    matches = [
      {
        device.product.id = "0x1141"
        api.v4l2.cap.card = "Integrated IR Camera: Integrate"
      }
    ]
    actions = {
      update-props = {
        priority.session = 900
      }
    }
  }
]
