---
- name: Enable base systemd services
  tags: [services, packages]
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ enabled_services | default([]) }}"
  loop_control:
    label: "{{ item }}"

- name: Enable host systemd services
  tags: [services, packages]
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ host_enabled_services | default([]) }}"
  loop_control:
    label: "{{ item }}"

- name: Enable systemd services without starting them
  tags: [services, packages]
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop: "{{ enabled_services_only | default([]) }}"
  loop_control:
    label: "{{ item }}"
