---
all:
  children:
    void:
      hosts:
        ikaros:
          ansible_connection: local
        nymph:
          ansible_connection: local

    desktop:
      hosts:
        ikaros:
          ansible_connection: local
        nymph:
          ansible_connection: local

    ubuntu:
      children:
        ubuntu_workstation:
        workstation_dev_wsl:
        ubuntu_server:

    fedora:
      children:
        fedora_workstation:

    workstation:
      children:
        workstation_host:
        workstation_dev:

    workstation_host:
      children:
        workstation_host_linux:
        workstation_host_windows:

    workstation_dev:
      children:
        workstation_dev_ubuntu:
        workstation_dev_fedora:
        workstation_dev_wsl:

    server:
      children:
        ubuntu_server:

    ubuntu_workstation:
      hosts:
        deadalus-ubuntu:
          ansible_connection: local

    fedora_workstation:
      hosts:
        deadalus-fedora:
          ansible_connection: local

    workstation_host_linux:
      hosts:
        deadalus-ubuntu:
          ansible_connection: local
        deadalus-fedora:
          ansible_connection: local

    workstation_dev_ubuntu:
      hosts:
        deadalus-ubuntu:
          ansible_connection: local

    workstation_dev_fedora:
      hosts:
        deadalus-fedora:
          ansible_connection: local

    workstation_host_windows:
      hosts:
        deadalus-win:

    workstation_dev_wsl:
      hosts:
        deadalus-wsl:
          ansible_connection: local

    ubuntu_server:
      hosts:
        prometheus:
          ansible_connection: local
