all:
  children:
    void:
      hosts:
        ikaros:
          ansible_connection: local
        nymph:
          ansible_connection: local

    ubuntu_workstation:
      hosts:
        deadalus:
          ansible_connection: local

    ubuntu_server:
      hosts:
        prometheus:
          ansible_connection: local
