---
all:
  children:
    platform_void:
      hosts: {}

    platform_fedora:
      hosts:
        ikaros:
          ansible_connection: local
        nymph:
          ansible_connection: local
        deadalus:
          ansible_connection: local

    platform_rocky:
      hosts:
        atlas:

    void:
      children:
        platform_void:

    fedora:
      children:
        platform_fedora:

    rocky:
      children:
        platform_rocky:

    graphical_desktop:
      hosts:
        ikaros:
          ansible_connection: local
        nymph:
          ansible_connection: local

    desktop:
      children:
        graphical_desktop:

    role_personal_workstation:
      hosts:
        ikaros:
          ansible_connection: local

    desktop_sway:
      hosts: {}

    desktop_niri:
      hosts: {}

    desktop_gnome:
      hosts:
        ikaros:
          ansible_connection: local
        nymph:
          ansible_connection: local

    ubuntu:
      children:
        ubuntu_server:

    workstation:
      children:
        workstation_dev:

    workstation_dev:
      children:
        workstation_dev_fedora:
        workstation_dev_wsl:

    server:
      children:
        ubuntu_server:

    workstation_dev_fedora:
      hosts:
        deadalus:
          ansible_connection: local

    workstation_dev_wsl:
      hosts:
        deadalus:
          ansible_connection: local

    ubuntu_server:
      hosts:
        prometheus:
          ansible_connection: local
