---
- name: Enable FreeBSD rc services
  tags: [services, packages]
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ host_enabled_services | default([]) }}"
  loop_control:
    label: "{{ item }}"
