---
- name: Enable base runit services
  tags: [services, packages]
  ansible.builtin.file:
    src: "/etc/sv/{{ item }}"
    dest: "/var/service/{{ item }}"
    state: link
  loop: "{{ enabled_services | default([]) }}"

- name: Enable host runit services
  tags: [services, packages]
  ansible.builtin.file:
    src: "/etc/sv/{{ item }}"
    dest: "/var/service/{{ item }}"
    state: link
  loop: "{{ host_enabled_services | default([]) }}"

- name: Enable emptty display manager for Void desktops
  tags: [services, packages, display-manager]
  ansible.builtin.file:
    src: /etc/sv/emptty
    dest: /var/service/emptty
    state: link
  when: "'desktop' in group_names"
