#!/bin/sh

cur="$(brightnessctl g 2>/dev/null)"
max="$(brightnessctl m 2>/dev/null)"

[ -n "$cur" ] || exit 0
[ -n "$max" ] || exit 0
[ "$max" -gt 0 ] || exit 0

pct=$((100 * cur / max))

echo "BL ${pct}%"
echo "BL ${pct}%"
echo "#6daeea"