---
- name: Reload SSH service
  ansible.builtin.systemd:
    name: sshd
    state: reloaded

- name: Reload NFS exports
  ansible.builtin.command:
    argv:
      - exportfs
      - -ra
  changed_when: true
  when: not ansible_check_mode

- name: Restart NFS server
  ansible.builtin.systemd:
    name: nfs-server
    state: restarted

- name: Restart NFS mount daemon
  ansible.builtin.systemd:
    name: nfs-mountd
    state: restarted
    daemon_reload: true

- name: Restart Samba service
  ansible.builtin.systemd:
    name: smb
    state: restarted

- name: Restart Atlas Syncthing service
  ansible.builtin.systemd:
    name: atlas-syncthing
    state: restarted
