# Formato video/audio - miglior qualità fino a 720p
ytdl-format=bestvideo[height<=?720]+bestaudio/best

# Sottotitoli
sub-visibility=yes
slang=it,en

# Download automatico sottotitoli (SRT)
ytdl-raw-options=write-subs=,write-auto-subs=,convert-subs=srt

# Layout e stile
sub-pos=100
sub-font-size=48

# Output
terminal=yes
