---
- name: Install packages on FreeBSD
  tags: [packages]
  community.general.pkgng:
    name: >-
      {{
        (
          (freebsd_packages_base | default([]))
          + (freebsd_development_packages | default([]))
          + (host_packages | default([]))
        )
        | unique
      }}
    state: present
