general {
  hide_cursor = true
}

background {
  monitor =
  path = ~/.config/hypr/wallpapers/maxresdefault.jpg
  blur_passes = 2
  blur_size = 4
}

input-field {
  monitor =
  size = 300, 48
  outline_thickness = 2
  dots_size = 0.25
  dots_spacing = 0.20
  outer_color = rgba(4a90d9ff)
  inner_color = rgba(1f1f28dd)
  font_color = rgba(ffffffff)
  fade_on_empty = false
  placeholder_text = Password
  position = 0, -80
  halign = center
  valign = center
}
